VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DevType"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Class DevType

Public name As String
Public damage As Integer
Public speed As Integer
Public guide As Integer
Public pwrNeed As Single
Public pwrGen As Single
Public cooldown As Integer
Public beam As Byte
Public seqs As Byte
Public xShiftMax As Integer
Public price As Long
Public upgCost As Single
Public imgName As String
Public scaleProjectile As Boolean
Public minProjScale As Single
Public maxProjScale As Single

'End of file


